version: '3.7'

volumes:
  dbbackups:
  postgis-data:

services:

  db:
    image: kartoza/postgis:12.0
    volumes:
    #To persist the data beyond the life of the container we configured a volume. 
    # This config will bind postgis-data to the "/var/lib/postgresql" 
      - postgis-data:/var/lib/postgresql
      - dbbackups:/backups
    environment:
      # If you need to create multiple database you can add coma separated databases eg gis,data
      - POSTGRES_DB=shoestrap
      - POSTGRES_USER=shoestrap
      - POSTGRES_PASS=shoestrap
      # Add extensions you need to be enabled by default in the DB. Default are the five specified below
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting
    ports:
      - 25432:5432
    restart: on-failure
    healthcheck:
      test: "exit 0"


  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - "db"
    command: >      
        bash -c "./scripts/wait-for-it.sh db:5432 -- python manage.py makemigrations
        && python manage.py migrate
        && python manage.py collectstatic --noinput --clear
        && gunicorn -b :8080 mysite.wsgi --reload"
    volumes:
      - .:/code
